### ISSUE TITLE
v2.0.0: compiler error when using stricter typing Model attributes signature

### ISSUE THREAD

**Issue by spinlud** [RobinBuschmann/sequelize-typescript#882]
It seems there are still problems when defining models with stricter typing syntax on attributes, as already reported here https://github.com/RobinBuschmann/sequelize-typescript/issues/844.
The following code does not compile:

```ts
import { Optional } from 'sequelize';
import { Sequelize, Model } from "sequelize-typescript";

interface PersonAttributes {
    id: number;
    name: string;
    country?: string;
}

interface PersonCreationAttributes extends Optional<PersonAttributes, 'country'> {}

class Person extends Model<PersonAttributes, PersonCreationAttributes> implements PersonAttributes {
    id!: number;
    name!: string;
    country?: string;
}


(async () => {
    const sequelize =  new Sequelize({
        dialect: 'mysql',
        host: 'localhost',
        port: 3306,
        database: 'testdb',
        username: 'admin',
        password: 'admin',
        logQueryParameters: true,
        logging: true,
    });

    await sequelize.authenticate();

    await sequelize.addModels([Person]); // <-- compiler complains

    await sequelize.close();
})();
```

![image](https://user-images.githubusercontent.com/12783208/104895000-a2a99300-5975-11eb-9d05-7e39d62c0b18.png)

See also:
* https://github.com/sequelize/sequelize/pull/12405
* https://github.com/RobinBuschmann/sequelize-typescript/pull/868

**Comment by RobinBuschmann** [comment]
Hey @spinlud, thanks for reporting. 

This doesn't seem to be a sequelize-typescript (only??) issue. Similar code also throws a compiler error with pure sequelize:
```ts
import {Model} from 'sequelize';

class Test extends Model<{test: string}> {}
class Test2 extends Model {}

Test2.findAll({
  include: [Test], // fails here
});
```
```
TS2322: Type 'typeof Test' is not assignable to type 'Includeable'.   
  Type 'typeof Test' is not assignable to type 'typeof Model'.     
    Types of construct signatures are incompatible.       
      Type 'new (values?: { test: string; } | undefined, options?: BuildOptions | undefined) => Test' is not assignable to type 'new <TModelAttributes extends {} = any, TCreationAttributes extends {} = TModelAttributes>(values?: TCreationAttributes | undefined, options?: BuildOptions | undefined) => Model<TModelAttributes, TCreationAttributes>'.        
      Types of parameters 'values' and 'values' are incompatible.           
        Type 'TCreationAttributes | undefined' is not assignable to type '{ test: string; } | undefined'.             
          Type 'TCreationAttributes' is not assignable to type '{ test: string; } | undefined'.               
            Type '{}' is not assignable to type '{ test: string; }'.                 
              Type 'TCreationAttributes' is not assignable to type '{ test: string; }'.                   
                Property 'test' is missing in type '{}' but required in type '{ test: string; }'.
```
Can anyone confirm?

The source of the problem seems to be the default value of generic TCreationAttributes in the definition of `Model`(sequelize).

See following example:
```ts
class Model<TModelAttributes = any, TCreationAttributes = TModelAttributes> {
    constructor(values?: TCreationAttributes) {}
}

class Test extends Model<{test: string}> {}

const addModel = (model: typeof Model) => {};

addModel(Test);
```
(see in [typescript playground](https://www.typescriptlang.org/play?ssl=9&ssc=16&pln=1&pc=1#code/MYGwhgzhAECyD2ATApiAPAFQSkBBALvgE4CWARgK77IwC80YAdgJ4A00GAwkcmPifEYFi5KjWj0sSVMNKVqEAHzQA3gChom6MEERiFYPnhEAFADcwICjQD8ALg7de-QbNEKAlKoC+a32tBIGAwafGhkAA9qRkQYbFQ0FQV8Bz1SRgBzb2UVfx1GPQZERHiQCWgTAFtpEAd8ZgAHZHgAMzgar1oc7wBuNTUwYtKTEL0PHqA))
If we change `TCreationAttributes = TModelAttributes` to `TCreationAttributes = any` the error disappears. Which is strange, since `TCreationAttributes` should be inferred to `any` anyway. 

I'm considering to just use `type ModelCtor<M extends Model = any> = (new (...args: any[]) => M)` instead of `export declare type ModelCtor<M extends Model = any> = (new () => M) & ModelType;`(so omitting `ModelType`, which is an alias for `typeof Model`) in sequelize-typescriot. This should give "enough" type safety, I think. But the IncludeOptions und the Includable type of sequelize need to be fixed as well: https://github.com/sequelize/sequelize/blob/main/types/lib/model.d.ts#L394

**Comment by RoelVB** [comment]
@RobinBuschmann I can confirm I'm seeing the same error with just `sequelize`.
Your playground example is very interesting 🤔

Found a related issue on the sequelize side:
https://github.com/sequelize/sequelize/issues/12842

**Comment by AlexanderProd** [comment]
It seems like, for now the only workaround is to use `//@ts-ignore` where this happens, right?

**Comment by RoelVB** [comment]
@AlexanderProd Yes, I've been ignoring the errors, didn't run into any problems yet.
But... PR #900 should fix this.

**Comment by AlexanderProd** [comment]
@AlexanderProd 
But #900 has been merged already, is it not included in version `2.1.0`? The problem still happens in `2.1.0` for me.

**Comment by RoelVB** [comment]
@AlexanderProd I just tested sequelize-typescript@2.1.0 with sequelize@6.5.0 and the problem described in this issue disappeared.

The typings issue is still there with includes. This is waiting for https://github.com/sequelize/sequelize/pull/13010

**Comment by KapitanOczywisty** [comment]
Issue should be fixed in sequelize 6.6.1, please verify. @Divlo

**Comment by spinlud** [comment]
Apologies for the delay.
Yes I can confirm that with the new versions the problem is solved. 

I've also updated [sequelize-typescript-generator](https://www.npmjs.com/package/sequelize-typescript-generator) to leverage the strict mode as well.
